name: qanony
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.5.3
  flutter_rating_bar: ^4.0.1
  introduction_screen: ^3.1.17
  image_picker: ^1.1.2
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  dio: ^5.8.0+1
  flutter_stripe: ^11.5.0
  flutter_dotenv: ^5.2.1
  share_plus: ^11.0.0
  pdf: ^3.11.3
  printing: ^5.14.2
  path_provider: ^2.1.5
  url_launcher: ^6.3.2
  app_links: ^6.4.0
  zego_uikit_prebuilt_call: ^4.16.5
  zego_uikit_signaling_plugin: ^2.8.15
  firebase_messaging: ^15.2.10
  flutter_callkit_incoming: ^2.5.6
  flutter_local_notifications: ^19.4.0
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/env/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Black.ttf
          weight: 900
        - asset: assets/fonts/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-ExtraLight.ttf
          weight: 200
